export const groupB = {
  "sayu": {
    "guide": "Sayu is the Anemo claymore whose whole kit is about rolling and healing - a combination no other unit offers. Her skill (Yoohoo Art: Fuuin Dash) lets her roll on press for a short tumble or hold to roll longer, dealing Anemo damage and, if she picks up an element mid-roll, gaining that element for a Swirl on release. Her burst (Yoohoo Art: Mujina Flurry) deals AoE Anemo and summons the Muji-Muji Daruma, which either heals low-HP characters or attacks enemies depending on team HP - making her a rare off-field healer.\n\nHer role is flexible: build her for Swirl damage with Elemental Mastery and Viridescent Venerer, or lean into the healing with HP and a Clam set. Because she is Anemo, she can hold VV and still contribute healing through her burst, which is a tidy two-in-one. Energy Recharge matters since her burst is her main sustain tool - typically 180-220%. Weapons favor Favonius Greatsword for the particles, or Sacrificial Greatsword to reset her skill.\n\nHer best teams are Swirl comps and any team that wants a self-sufficient Anemo healer, including Sucrose-style driver setups and exploration parties where her roll is also a fast travel tool. Where she struggles: her damage is low even for an Anemo unit, her healing is spread thin rather than bursty, and her roll can be awkward to control. She is a comfort and utility pick, not a ceiling unit."
  },
  "mika": {
    "guide": "Mika is a Cryo polearm support built around two things: healing and attack-speed buffing for Physical carries. His skill (Flowfrost Arrow) has a tap form that creates a Flowfrost Arrow following the active character and dealing Cryo, and a hold form that deals more and grants його first ascension buff - Skyfeather Song - which raises the active character's Physical DMG based on Mika's ATK and heals them. His burst (Skyfeather Sonnet) heals the team and grants Reluctant Benison, speeding up normal attack speed, with his C6 adding a large ATK SPD and Physical boost.\n\nThat makes him the dedicated enabler for Physical DPS units - Eula, Freminet, Razor - where the attack-speed buff directly increases rotation damage. His buff scales with his ATK, so a meaningful chunk of his build goes to ATK% Sands and an ATK weapon, while HP and Energy Recharge keep his healing and burst online.\n\nFor sets, 4pc Noblesse Oblige supports the team, Song of Days Past amplifies his healing, and Ocean-Hued Clam turns that healing into damage. Favonius Lance is the safest weapon for his own energy, with Skyward Spine as an alternative. Energy needs are high - around 200-240% - because his 80-cost burst is his main value.\n\nWhere he struggles: he is locked to Physical teams, his buffs do nothing for non-Physical carries, and his personal damage is negligible. Outside Eula and Freminet he has little reason to be on the team."
  },
  "qiqi": {
    "guide": "Qiqi is the poster child for over-healing: her numbers are enormous, but her kit is slow and clunky. Her skill (Herald of Frost) applies Cryo, heals the active character, and marks enemies with the Fortune-Preserving Talisman, so that any hit on those enemies heals the attacker. Her burst (Preserver of Fortune) is a large AoE heal plus a party-wide version of the talisman mark, making her one of the strongest raw healers in the game.\n\nThe tradeoff is tempo. Her skill has a long cooldown and her burst is 80 cost, so she needs heavy Energy Recharge - often 200% or more - and her healing only really kicks in after you have marked enemies, which delays it. Build her for HP% and Healing Bonus, with a Healing Bonus circlet; 2pc Maiden Beloved plus 2pc Tenacity of the Millelith is standard, and Ocean-Hued Clam gives her some offense. Aquila Favonia is her premium weapon for the ATK and healing, with Sacrificial Sword or Favonius Sword for energy.\n\nHer best homes are teams that want a bulletproof Cryo enabler and sustain, including Superconduct Physical teams and Freeze. Where she struggles: her damage is essentially zero, her application is slow, and modern healers like Charlotte or Yaoyao do her job with far better uptime. She remains a comfort pick for players who want to never die."
  },
  "razor": {
    "guide": "Razor is the wolf boy, a Physical claymore carry whose kit is built entirely around his Electro-infused burst mode. His skill (Claw and Thunder) on press deals Electro and generates particles; on hold (Lightning Fang) he summons the Wolf Within, which boosts his Electro, reduces nearby enemy DEF, and gives him energy. His burst (Lightning Fang) flips him into an Electro state that greatly increases his attack speed and interruption resistance - this is his damage window.\n\nBecause his field buffs Electro and shreds DEF, he pairs naturally with Electro batteries like Fischl and Beidou, plus a Cryo unit for Superconduct to cut Physical RES, and Bennett for ATK. His fourth ascension passive reduces his skill cooldown when he takes damage, which rewards aggressive play.\n\nBuild him for Physical: ATK% Sands, Physical DMG Goblet, CRIT Circlet, with 4pc Pale Flame for skill-scaling or 2pc Pale Flame plus 2pc Bloodstained Chivalry. Energy needs are moderate because his burst is self-sustaining. Wolf's Gravestone is his best weapon, with Serpent Spine, Song of Broken Pines and R5 Snow-Tombed Starsilver as strong budget picks.\n\nWhere he struggles: he is a selfish on-field carry with no off-field value, his Electro state can interfere with reactions if you are not careful, and he is outclassed by newer Physical units like Eula and Freminet at high investment. As a free starter DPS, though, he remains a solid farmer."
  },
  "amber": {
    "guide": "Amber is the free Pyro bow whose reputation underestimates her utility. Her skill (Explosive Puppet) drops Baron Bunny, a taunt that draws enemy fire and explodes for AoE Pyro - a reliable off-field Pyro application and crowd control tool. Her burst (Fiery Rain) rains Pyro in a small area for several seconds, giving her genuine off-field Pyro uptime that few other bow users match.\n\nHer biggest hidden value is constellation six: it makes her charged attacks apply Pyro to enemies, turning her into a Vaporize enabler for carry units like Hu Tao or Diluc. Build her for EM in that role to amplify the reactions, or for ATK if you want her own burst damage. 4pc Wanderer's Troupe rewards her charged attacks, while 2pc ATK plus 2pc EM is the budget mix. Weapons favor Hamayumi, Sharpshooter's Oath, or Elegy for the End and The Stringless for support.\n\nHer best teams are as a Pyro applier in Vaporize comps, a C6 enabler, and an exploration pick thanks to her gliding passive. Where she struggles: her personal damage is low, Baron Bunny has a long cooldown, and she is easily outclassed by every other Pyro unit in pure DPS. She is a toolkit character - useful precisely because she is free and flexible."
  },
  "lisa": {
    "guide": "Lisa is the free Electro catalyst whose kit is built around stacking Conductive and bursting. Her skill (Violet Arc) on press deals a single hit and applies one stack of Conductive; on hold it consumes all stacks for a large AoE discharge. Her burst (Catharsis) creates a field that continuously applies Conductive and deals Electro, and her passive reduces enemy DEF whenever she hits a Conductive target - making her a budget DEF shredder.\n\nBecause her burst is a long-duration field, she works as an off-field Electro applier in Electro-Charged and Aggravate teams. Build her for Elemental Mastery in Aggravate (where her field keeps enemies infused) or ATK for general use. 4pc Golden Troupe boosts her skill-based damage, while 2pc Electro plus 2pc ATK is the simple route. Hakushin Ring is a strong support weapon that buffs the team's Electro or Dendro, with Mappa Mare and The Widsith as alternatives.\n\nHer best homes are Aggravate cores with Nahida and a Quicken trigger, and Electro-Charged teams. Where she struggles: her hold-skill is clunky and easy to mistime, her application is single-target, and her DEF shred only triggers on Conductive hits. She is a serviceable free unit but rarely a ceiling pick."
  },
  "thoma": {
    "guide": "Thoma is the Pyro polearm shielder whose value compounds the longer a fight runs. His skill (Blazing Blessing) grants a shield that follows the active character and deals Pyro damage, and his burst (Crimson Ooyoroi) creates a larger shield plus Fiery Collapse - coordinated attacks that deal Pyro whenever the active character's normal attacks land. His shields stack rather than refresh, so his uptime improves the longer he stays on the team.\n\nTwo passives define his build. His shield strength scales with Max HP, so HP% is his core stat, and his A4 grants a normal attack DMG bonus to the active character while his shield is up - turning him into a quiet attacker-speed buffer. That makes him a natural partner for normal-attack carries and for Burgeon teams, where his Pyro application feeds Bloom cores.\n\nFor sets, 4pc Emblem of Severed Fate keeps his burst up (he wants around 180-220% ER), while 2pc Tenacity plus 2pc Emblem is the support mix. Favonius Lance is the best weapon for his energy and the team's, with Staff of Homa and Engulfing Lightning as premium options.\n\nHis best teams are Burgeon (with Nilou or a Dendro core), Vaporize, and any comp wanting a Pyro shield. Where he struggles: his personal damage is low, his shields are weaker than Zhongli's, and he needs significant ER investment to feel smooth."
  },
  "heizou": {
    "guide": "Heizou is the only Anemo catalyst on-field DPS, and his damage comes from stacking Declension. His passive grants Declension stacks whenever a Swirl happens near him or when his skill hits - up to four - and his skill (Heartstring Noodles) consumes those stacks for a stronger, larger Anemo strike. His burst (Fudou Style: Windwalker Kick) deals AoE Anemo and refreshes the field. At four stacks his skill becomes a big nuke, so the loop is simple: Swirl to build stacks, then skill to cash them in.\n\nBecause he is Anemo and wants to Swirl, build him for the reaction: Elemental Mastery with 4pc Viridescent Venerer, or 4pc Desert Pavilion for raw Anemo damage. ATK% Sands, Anemo DMG Goblet and CRIT Circlet are standard, with modest Energy Recharge since his burst is a bonus rather than his core. Lost Prayer, Kagura's Verity and The Widsith are his best weapons, with Solar Pearl or Mappa Mare as free options.\n\nHis best teams are Swirl DPS, Aggravate with Nahida, and Quicken comps where he both triggers and benefits from the reaction. Where he struggles: he is a melee catalyst with short range, his damage falls off against enemies that resist Swirl, and he has no shielding or healing. He is a fun, self-sufficient hypercarry for Anemo fans."
  },
  "candace": {
    "guide": "Candace is the Hydro polearm whose claim to fame is normal-attack infusion. Her skill (Sacred Rite: Heron's Sanctum) on hold creates a shield and deals Hydro, and her passive makes the shielded active character's attacks deal Hydro. Her burst (Sacred Rite: Wagtail's Tide) grants Prayer of the Crimson Crown, infusing the active character's normal attacks with Hydro and boosting their ATK based on Candace's Max HP - a rare normal-attack buff that also changes the element of the carry's hits.\n\nThat makes her a specialist for normal-attack carries who want Hydro application without swapping off-field - Yoimiya, Itto, and even Ayato benefit. Build her for HP% and Energy Recharge, because both her shield and her ATK buff scale with HP and her 80-cost burst needs to be up often. 4pc Emblem of Severed Fate is the standard for burst uptime, with Tenacity of the Millelith as a support option. Favonius Lance is the safest weapon, with Staff of Homa or Key of Khaj-Nisut as premium picks.\n\nWhere she struggles: her infusion only affects normal attacks, so burst or skill-focused carries gain nothing, and her personal damage is negligible. She is a niche enabler whose value is entirely in the right auto-attack comp."
  },
  "chongyun": {
    "guide": "Chongyun is the Cryo claymore whose skill turns melee characters into Cryo units - a unique enabler role. His skill (Spirit Blade: Chonghua's Layered Frost) creates a field that infuses the normal attacks of sword, claymore and polearm characters with Cryo, letting Pyro carries like Hu Tao, Diluc or Ganyu trigger Melt on every hit. His burst (Spirit Blade: Cloud-Parting Star) deals AoE Cryo and creates a second field that slows enemies and applies Cryo.\n\nThat infusion is his whole identity. As a support he wants 4pc Noblesse Oblige to buff the team; as a DPS he runs 4pc Blizzard Strayer for Freeze. Stats are ATK% Sands, Cryo DMG Goblet, CRIT Circlet, with Energy Recharge around 150-180% for his 80-cost burst. Wolf's Gravestone and Serpent Spine are his best weapons, with R5 Lithic Blade and Sacrificial Greatsword as budget options.\n\nHis best teams are Melt comps where he enables a Pyro carry, Superconduct Physical teams, and Freeze cores. Where he struggles: his infusion can clash with other elements (you generally cannot run him alongside another melee Cryo infuser), his field has a radius limit, and his own damage is modest compared to dedicated Cryo DPS. He is a specialist tool, excellent when his infusion is exactly what the team needs."
  }
};
