export const groupA = {
  "wriothesley": {
    "guide": "Wriothesley is the only Cryo catalyst on-field DPS, and the mechanic that defines him is the HP line he draws at 50%. His skill (Darkgold Wolfbite) puts him into the Chill of Punishment state, and while his HP stays above half his charged attacks gain the Recipe of Survival bonus - a large, ATK-scaled damage increase. Drop below half and that bonus is replaced by the Recipe of Resurrection, which instead heals him on the same charged attacks. Learning to ride the 50% line is the whole build.\n\nHis burst (Black-Clad Brute) keeps the momentum going: it deals AoE Cryo, taunts enemies with the Icefang Rush, and heals him based on his Max HP. Because his skill and burst both move HP around, he self-triggers HP-fluctuation gear - which is exactly why 4pc Marechaussee Hunter is his best set even though it was designed for Furina teams. Blizzard Strayer is the alternative if you are not running a shielder or Furina.\n\nFor stats, run ATK% Sands, Cryo DMG Goblet, CRIT Circlet. His energy needs are low for a 5-star carry - around 110-130% - because his burst is only 60 cost and he generates his own particles. Weapons follow the stat-stick logic: Cashflow Supervisor is his signature and gives the HP ceiling he wants, while Tidal Shadow, Ballad of the Fjords and even Lost Prayer are all strong.\n\nHis best teams lean on Cryo resonance and a shielder so he can charge-attack safely. Furina is an outstanding partner because she both feeds his HP swings and benefits from them, with Shenhe, Kazuha or Xingqiu/Yelan filling the rest for Freeze. Where he struggles: against enemies that punish standing still, and in content where you cannot control his HP, his damage drops sharply."
  },
  "lyney": {
    "guide": "Lyney is a Fontaine Pyro bow DPS whose entire kit is built around one prop: the Grin-Malkin Hat. His skill (Boum-ooom!) summons that hat, which taunts enemies and - crucially - enables his enhanced charged attacks. With the hat on the field, his charged attack becomes a Flare-Up shot that ignores charge time and deals AoE Pyro, so the rotation is skill, then two or three immediate charged attacks, then swap.\n\nHis passive, Triangle of Enchantment, is why he wants the hat and a second Pyro teammate. Each Pyro construct or hat on the field grants him a stacking Pyro DMG Bonus, reaching a meaningful bump at C0 and far more at higher constellations. His burst (Wondrous Trick: Miracle Parade) drops a big AoE Pyro and respawns a hat, which is the easiest way to keep the bonus stacked.\n\nBuild him like a normal Pyro carry: ATK% Sands, Pyro DMG Goblet, CRIT Circlet, with Energy Recharge landing around 110-130% so his 60-cost burst stays available. 4pc Marechausse Hunter is strong because his passive periodically drains his HP, and 4pc Crimson Witch is the choice for Vaporize. His signature, The First Great Magic, is tailor-made for him; Aqua Simulacra, Thundering Pulse and Polar Star all work.\n\nHis core teams are mono-Pyro (Bennett + Xiangling for Vaporize, plus Kazuha or Zhongli) or a Furina variant. Where he struggles: he is a single-target bow user with weak AoE, and he is awkward to play without a shielder because aiming charged attacks leaves him exposed."
  },
  "chiori": {
    "guide": "Chiori is a Geo sword sub-DPS who fights through summoned dolls rather than her own body. Her skill (Fluttering Hasode) has two forms: tap places a doll at her location, while hold sends a doll out, has it strike, and - if you stand on the created platform - lets her jump to a second doll. Both dolls deal off-field Geo damage, and that is where almost all of her value sits.\n\nThe single most important rule for Chiori is the Geo teammate requirement. Her passive grants an extra doll whenever another Geo character is in the party, taking her from one off-field attacker to two. Without a second Geo unit she loses roughly half her damage, so she is almost never worth running in a flex slot - pair her with Zhongli, Albedo, Itto, Navia or Noelle.\n\nHer burst (Hiyoriboshi no Michi) adds a third burst of AoE Geo and refreshes the field. For stats, ATK% Sands, Geo DMG Goblet and CRIT Circlet are standard, with modest Energy Recharge because her 80-cost burst is a nice-to-have rather than her core. 4pc Golden Troupe maximizes her skill damage since the dolls count as Elemental Skill hits; 2pc Geo plus 2pc ATK is the budget option. Her signature Uraku Misugiri is far and away her best weapon, with Haran Geppaku Futsu, Mistsplitter Reforged and Wolf-Fang as alternatives.\n\nWhere she struggles: she is locked to Geo teams, her dolls can miss fast or flying enemies, and she offers no healing or shielding of her own."
  },
  "dehya": {
    "guide": "Dehya is a Pyro claymore whose kit is honest about its flaws: she is a defensive enabler first and a damage dealer a distant second. Her skill (Molten Inferno) creates the Fiery Sanctum field, which redirects a portion of incoming damage away from the active character and reduces it. Within the field, her coordinated Leonine Bite attacks trigger when the active character's normal attacks land, giving modest off-field Pyro application.\n\nThe catch is well known: once you cast her skill, the active character is locked inside her field and cannot be swapped out normally, which disrupts most team rotations. That is why her strongest home is as a Burgeon trigger for Nilou teams, where the field's Pyro application feedsBloom cores without needing her on field for long, or as a budget Pyro unit in casual content.\n\nHer burst (Leonine Bite) deals AoE Pyro and summons a larger field, so build her for HP and Energy Recharge if you want burst uptime, or ATK for personal damage. 4pc Emblem of Severed Fate is the standard for burst-focused builds, while Tenacity of the Millelith turns her into a support. Weapons are flexible: Wolf's Gravestone, Beacon of the Reed Sea, or the craftable Mailed Flower all perform.\n\nWhere she struggles: her damage per screen is low, her field disrupts rotations, and she is generally outclassed by every other Pyro unit in dedicated DPS roles. Use her for comfort and Burgeon, not for ceilings."
  },
  "kaeya": {
    "guide": "Kaeya is the free starter Cryo unit who quietly does two jobs better than most 5-stars: he batteries the team and he applies Cryo off-field. His skill (Frostgnaw) hits twice and generates three Cryo particles on press, which makes him one of the few units who can feed his own burst reliably. His burst (Glacial Waltz) sends out orbiting icicles for 12 seconds of continuous off-field Cryo - long enough to cover most rotations.\n\nBecause his value is application and energy rather than raw damage, his build is flexible. 4pc Blizzard Strayer turns him into a respectable Freeze DPS, while 4pc Emblem of Severed Fate or Noblesse Oblige support the team. Aim for enough Energy Recharge to keep his 60-cost burst up - roughly 130-160% depending on how many other Cryo units you run - and use Favonius Sword to hand those particles to a carry like Ayaka or Ganyu.\n\nHis best teams are Freeze cores (Ayaka, Ganyu, Mona), Superconduct setups for Physical carries (Eula, Razor, Freminet), and as a universal Cryo battery. He also fits Melt and Taser comps where off-field Cryo is needed.\n\nWhere he struggles: his personal damage falls off at high investment compared to dedicated 5-star Cryo units, and his burst icicles can miss fast-moving or flying enemies. As a battery and enabler, though, he remains one of the best value units in the game."
  },
  "barbara": {
    "guide": "Barbara is the quintessential Hydro healer, and her job is keeping the team alive while enabling Hydro reactions. Her skill (Let the Show Begin) has two modes: the default heals the active character over time and applies Hydro to nearby enemies every few seconds, while the alternate creates a stronger field that also heals the whole party. Her burst (Shining Miracle) is a full-party heal scaled off her Max HP.\n\nThe famous downside is the self-application: while her skill field is active, Barbara and anyone standing in it become Hydro-imbued, which can trigger unwanted Freeze or self-Swirl. The standard fix is to step out of the field during combat, or to accept it as a Freeze enabler in Barbara + Cryo teams.\n\nBuild her for HP and Healing Bonus, with a circlet that prioritizes healing. 2pc Maiden Beloved plus 2pc Tenacity of the Millelith is the default, while Ocean-Hued Clam converts her healing into damage. Her signature-class support weapon is Thrilling Tales of Dragon Slayers, which gives a massive ATK buff to the next character swapped in; Prototype Amber and Hakushin Ring are alternatives.\n\nWhere she struggles: she has no shielding, her Hydro self-application can be a liability, and her damage is negligible. She is a pure comfort pick - excellent for exploration and casual content, less ideal in tight endgame rotations where a shielder or off-field Hydro is preferred."
  },
  "ningguang": {
    "guide": "Ningguang is the Geo catalyst queen whose entire kit is about the Jade Screen. Her skill (Jade Screen) raises a barrier that blocks enemy projectiles and, more importantly, buffs her charged attack by 12% for a few seconds whenever a gem passes through it. Her charged attack fires six Star Jades that home in and deal Geo damage. Her burst (Starshatter) detonates the screen for AoE Geo and generates seven Star Jades instantly, which is a huge on-demand nuke.\n\nBecause her screen is the core, placement matters: cast it so her charged attacks pass through it for the damage bonus, then burst to convert it into a wave of projectiles. Her passive also makes her a strong explorer - she reveals ore on the map and takes less damage from falling rocks.\n\nBuild her like a normal Geo carry: ATK% Sands, Geo DMG Goblet, CRIT Circlet, with Energy Recharge around 115-130% for the 80-cost burst. 4pc Archaic Petra (stealing elemental resonances) is her strongest set, while 2pc Geo plus 2pc ATK is the safe fallback. Weapons favor stat sticks: Lost Prayer to the Sacred, Memory of Dust, Solar Pearl and Skyward Atlas all perform well.\n\nHer best teams are mono-Geo with Zhongli, Albedo, Gorou or Navia, and she shines in Geo resonance. Where she struggles: she is single-target, her screen can be destroyed by enemies, and she is weak against flying enemies her gems cannot reach."
  },
  "noelle": {
    "guide": "Noelle is the maid who does everything, and her ceiling depends entirely on constellation six. Her skill (Breastplate) grants a shield that scales with DEF and converts her normal attacks to Geo while it is active. Her burst (Sweeping Time) is the payoff: for 15 seconds her attacks gain a Geo infusion, her ATK scales with her DEF, and every hit heals the entire party. Without C6 her burst does not grant the Geo infusion, which is why pre-C6 Noelle is a healer-shielder, not a DPS.\n\nAt C6, build her as a true Geo carry. 4pc Husk of Opulent Dreams is mandatory because it stacks DEF and Geo DMG from her own skill, and her stats become DEF% Sands, Geo DMG Goblet, CRIT Circlet - unusual for a DPS but correct, since her burst converts DEF to ATK. Her fourth ascension passive also lets her heal and occasionally shield on hit during the burst. Weapons are Redhorn Stonethresher (signature-class), Serpent Spine or Whiteblind.\n\nHer teams are mono-Geo: Gorou for the DEF and Geo buffs, Albedo for off-field damage, Zhongli for shielding and resistance shred. Where she struggles before C6: her damage is low and her burst is expensive (80 cost), so she needs heavy Energy Recharge and a battery. At C6 she becomes a genuinely strong, self-sufficient carry."
  },
  "diona": {
    "guide": "Diona is the Cryo bow who splits her value between shielding and healing - and she is the budget version of every Cryo support rolled into one. Her skill (Icy Paws) fires shielding cat paws: tap creates two, hold creates five, and each also throws Cryo energy at enemies. Her burst (Signature Mix) creates a Drunken Mist field that heals the active character and grants a Cryo DMG Bonus while slowing enemies, acting as both sustain and a mini-ttds for Cryo carries.\n\nHer build depends on the role. For shielding, stack HP% because her shield scales with Max HP, and use Tenacity of the Millelith to add an ATK buff on top. For energy, Favonius Warbow is excellent because her paws generate particles and the weapon refund lets her battery the team. 2pc Maiden plus 2pc Tenacity is the common healer setup; Noblesse Oblige works if she is the burst buffer.\n\nHer best homes are Freeze teams (where her shield plus Cryo application is comfortable), Physical teams (Superconduct plus healing), and as a Cryo battery for Ayaka or Ganyu. Where she struggles: her shield, while good, is weaker than Zhongli's, her burst healing is modest, and her personal damage is negligible. She competes directly with Layla and Shenhe depending on what the team needs."
  },
  "yun-jin": {
    "guide": "Yun Jin is a Geo polearm support whose entire purpose is buffing normal attacks. Her burst (Cliffbreaker's Banner) grants Flying Cloud Flag Formation to nearby party members, increasing their normal attack damage by an amount that scales with her own DEF. That makes her a direct buffer for any carry who lives on normal attacks - Yoimiya, Itto, and Physical units all benefit disproportionately.\n\nHer skill (Opening Flourish) creates a shield that also scales with DEF, so her whole build funnels into one stat. Her passive further rewards DEF by adding a flat normal attack damage bonus when her shield is active, and Geo resonance plus a second Geo unit extends her buff duration. Unlike most buffers, she does not care about the carry's element - only that they auto-attack.\n\nBuild her full DEF%: DEF% Sands, DEF% Goblet, DEF% Circlet if you can keep CRIT for her tiny personal damage, otherwise DEF% everywhere, with Energy Recharge around 180-220% because her burst is 80 cost and her personal particle generation is low. 4pc Husk of Opulent Dreams is her best set for obvious reasons. Staff of Homa is the premium weapon, with Favonius Lance and Engulfing Lightning as strong alternates.\n\nWhere she struggles: her buff only helps normal-attack damage, so she is useless for burst or skill-focused carries, and her own energy needs are demanding. She is a niche but powerful pick for the right auto-attacker."
  }
};
