export const groupC = {
  "xinyan": {
    "guide": "Xinyan is the rock-and-roll Pyro claymore who combines shielding with Physical damage. Her skill (Sweeping Fervor) grants a shield that scales with DEF and deals Pyro, and the number of enemies hit determines her Riff stacks: zero gives an ATK bonus, one adds Physical DMG, and two or more also shreds enemy Physical RES. Her burst (Riff Revolution) deals AoE Pyro and applies Pyro to nearby enemies.\n\nHer fourth ascension passive grants a Physical DMG Bonus to shielded characters, and her C4 lowers enemy Physical RES further, so she both shields and amplifies a Physical carry. Build her either as a Physical DPS with 4pc Pale Flame (or 2pc Pale Flame plus 2pc Bloodstained) and ATK%/Physical/CRIT, or as a support with 4pc Tenacity of the Millelith. Serpent Spine and Wolf's Gravestone are her best weapons, with R5 Debate Club as a strong free pick.\n\nHer best teams are Physical cores alongside Rosaria or Fischl for Superconduct, and she fits in comfort comps that want a shield plus RES shred. Where she struggles: her shielding is mediocre, her Riff stacks require hitting multiple enemies to reach the RES shred, and she is outclassed by dedicated Physical units. She is a fun hybrid with a clear niche at C4."
  },
  "yanfei": {
    "guide": "Yanfei is the Pyro catalyst law-enforcer whose damage rides on Scarlet Seals. She accumulates up to three seals from normal attacks, her skill, and her burst; her charged attack (Seal Slash) consumes them for bonus damage and applies Pyro. Her skill (Signed Edict) grants a shield and adds a seal, while her burst (Done Deal) deals AoE Pyro, grants max seals and extends their duration - making her a sustained charged-attack DPS.\n\nBecause her charged attacks are her core, build her like a catalyst charged-attack carry: 4pc Wanderer's Troupe is her best set, with 4pc Crimson Witch for Vaporize. ATK% Sands, Pyro DMG Goblet, CRIT Circlet, and Energy Recharge around 115-135% for her 80-cost burst. Lost Prayer, Skyward Atlas and Solar Pearl are her best weapons, with Memory of Dust and A Thousand Floating Dreams as alternatives.\n\nHer best teams are Vaporize with Xingqiu or Yelan, Mono Pyro, and Overload. Where she struggles: she is single-target, her charged attacks are slow and stamina-hungry, and she has no shielding or healing. She is a strong 4-star Pyro DPS but competes with Hu Tao and Lyney for the same role."
  },
  "kujou-sara": {
    "guide": "Kujou Sara is the Electro bow support whose value is an ATK buff that scales with her own ATK. Her skill (Tengu Stormcall) on tap fires a crow strike; on hold it creates a Crowfeather Cover that, when the active character's attack lands on it, grants an ATK bonus based on Sara's ATK stat. Her burst (Subzero Barrage) deals AoE Electro and leaves a Crowfeather that buffs the next attacker - effectively a team-wide ATK boost for Electro carries.\n\nBecause her buff scales with ATK, she wants ATK% Sands and an ATK weapon, plus enough Energy Recharge (around 180-220%) to keep her 80-cost burst up. 4pc Emblem of Severed Fate is the standard for burst uptime, with 2pc ATK plus 2pc Emblem as a fallback. Skyward Harp, Hamayumi and Mouun's Moon are her best weapons, with Elegy for the End and Favonius Warbow as support options.\n\nHer best teams are Electro carry buffers - Raiden, Keqing, Cyno, and even Xiao to a degree - where the ATK buff directly raises their damage. Where she struggles: her buff only helps the active character who triggers the Crowfeather, her application is single-target, and at C0 her ER needs are demanding. She is a dedicated Electro support with no flex value."
  },
  "collei": {
    "guide": "Collei is the free Dendro bow sub-DPS and the budget version of every Dendro enabler. Her skill (Floral Brush) throws a boomerang that deals Dendro on the way out and back, and her burst (Trump-Card Kitty) creates a Cuilein-Anbar zone that applies Dendro periodically for its duration. Her fourth ascension passive refunds energy when her skill hits, smoothing her rotations.\n\nBecause she is a pure enabler, build her for Elemental Mastery and either Dendro DMG or Energy Recharge. 4pc Deepwood Memories is her best set since it shreds Dendro RES for the whole team, while 2pc EM plus 2pc Dendro is the budget route. Elegy for the End is her premium support weapon, with The Stringless and Favonius Warbow as strong options.\n\nHer best teams are Dendro cores: Quicken and Spread with Tighnari, Nahida or Alhaitham, and Bloom variants. Where she struggles: her personal damage is low, her application has gaps between skill and burst, and she is outclassed by Nahida in sustained Dendro uptime. As a free unit, though, she is the easiest way to enable Dendro reactions early on."
  },
  "sigewinne": {
    "guide": "Sigewinne is the Hydro bow healer built around the Bond of Life mechanic. Her kit heals the team and, through her burst, grants an ATK bonus to all party members that scales with her Max HP and the amount of Bond of Life active - which is why she pairs so naturally with Furina, whose entire kit generates Bond of Life. Her skill fires healing bolts, and her A4 grants a Hydro DMG Bonus to the team based on her stats.\n\nBuild her for HP% and Healing Bonus, with a Healing Bonus circlet and enough Energy Recharge to keep her burst available. 4pc Tenacity of the Millelith is the standard support set, while Song of Days Past or Ocean-Hued Clam convert her healing into value. Aqua Simulacra is her best weapon, with Favonius Warbow, Sacrificial Bow and even Recurve Bow (for HP) as alternatives.\n\nHer best home is Furina teams, where she both heals the HP drain and amplifies the ATK buff Furina provides - a rare case of two units designed to enable each other. Where she struggles: her personal damage is negligible, her kit is almost entirely about healing and buffing, and outside Bond-of-Life teams her ATK bonus has little to scale from. She is a specialized premium healer."
  },
  "sethos": {
    "guide": "Sethos is the Electro bow on-field DPS who plays like a catalyst carry. After his skill (Secret Rite: Twilight Silt), his charged attack becomes a powerful beam-like shot (the Psiset) that costs no stamina and deals heavy Electro - and his fourth ascension passive speeds up his normal attacks after using his skill, letting him weave autos into the rotation. His burst boosts his charged-attack CRIT DMG, making the loop skill, normal attacks, then charged beam.\n\nBecause he wants to Aggravate, build him for Elemental Mastery and Electro: 4pc Gilded Dreams or 4pc Wanderer's Troupe, with ATK%/Electro/CRIT or an EM focus. Energy Recharge around 120-140% is enough since his burst is a bonus. Hunter's Path is his signature, but R5 Slingshot is a famously strong free pick thanks to its ER and damage substats, with The Stringless and Polar Star as alternatives.\n\nHis best teams are Aggravate with Nahida and a Quicken partner, and he is a natural duo with Tighnari. Where he struggles: his damage window is gated behind his skill, his single-target focus is weak against crowds, and he needs Dendro to reach his ceiling. He is a solid free-to-play-friendly Electro carry."
  },
  "kachina": {
    "guide": "Kachina is the Natlan Geo polearm sub-DPS who fights through her contraption, Turbo Twirly. Her skill (Go, Pussycat!) summons the Twirly, which deals Geo damage and moves around the field; while it is active and she is off-field, her passive increases its damage and builds Nightsoul points (Mountain King's Dewgar), tying her into Natlan team mechanics. Her burst deals AoE Geo and refreshes the field.\n\nBecause she is a Nightsoul unit and a Geo applier, her best role is the Scroll holder in Natlan reaction teams or a flexible Geo unit elsewhere. Build her for Energy Recharge and Geo damage: 4pc Scroll of the Hero of Cinder City is her strongest set when the team's reactions match her Geo, while 2pc Geo plus 2pc ATK is the fallback. Favonius Lance and Deathmatch are her best weapons, with Blackcliff Pole as a free option.\n\nHer best teams are Natlan comps (Mavuika, Kinich, Varesa) where she provides Scroll buffs and Nightsoul synergy, and Geo resonance teams. Where she struggles: her personal damage is low, her contraption can miss fast enemies, and she offers no healing or shielding. She is a competent, accessible Natlan enabler."
  },
  "ororon": {
    "guide": "Ororon is the Natlan Electro bow sub-DPS built around Nightsoul mechanics. His skill (Night's Sling) summons Cirrus, a bat that deals off-field Electro, and his passive triggers a coordinated Electro attack whenever an ally triggers a Nightsoul Burst nearby - making him a passive damage dealer that rewards playing Natlan units. His burst extends his Electro application and buffs the team.\n\nBecause he is a Nightsoul unit, his best role is the Scroll holder in Natlan reaction teams, where his off-field Electro enables Vaporize, Overload or Electro-Charged while he buffs the team. Build him for Elemental Mastery and Electro: 4pc Scroll of the Hero of Cinder City is his strongest set, with 2pc Electro plus 2pc ATK as the fallback. Chain Breaker is his signature, with Favonius Warbow, The Stringless and Elegy for the End as alternatives.\n\nHis best teams are Natlan comps - Mavuika, Kinich, Varesa, and Chevreuse Overload - where his Electro and Scroll buffs multiply team damage. Where he struggles: outside Nightsoul teams his value drops, his personal damage is modest, and he has no shielding or healing. He is a focused Natlan enabler."
  },
  "lan-yan": {
    "guide": "Lan Yan is the Liyue Anemo catalyst whose signature is a swirling shield. Her skill (Lustrous Moonrise) creates a shield that absorbs all elemental types and, when struck, absorbs the element it was hit with to boost her Swirl damage - a unique defensive-Swirl hybrid. Her burst deals AoE Anemo and refreshes the field, and her fourth ascension passive increases shield strength and Swirl damage based on her Elemental Mastery.\n\nThat dual identity means she can be built two ways: as a Swirl driver with 4pc Viridescent Venerer and full Elemental Mastery, or as a shield support with 4pc Tenacity of the Millelith and HP. Weapons follow the role - Wandering Evenstar and Sacrificial Fragments for Swirl, Hakushin Ring or Mappa Mare as free options, with Lost Prayer as a stat stick.\n\nHer best teams are Swirl comps, Anemo-flex slots, and any team wanting a shield plus crowd control. Where she struggles: her shield, while versatile, is weaker than Zhongli's, her Swirl damage is modest for an Anemo unit, and she competes with Kazuha and Sucrose for the VV role. She is a flexible, shield-bearing Anemo option."
  },
  "mizuki": {
    "guide": "Mizuki is the Inazuma Anemo catalyst who fights in a drifting, wind-walking state. Her skill (Passionate Appeal) puts her into a hovering state where she moves freely and deals Anemo damage with her attacks, and her fourth ascension passive grants a team-wide Elemental Mastery buff after she uses her skill - making her a rare EM-boosting Anemo unit. Her burst deals AoE Anemo and extends the field.\n\nBecause she buffs EM and wants to Swirl, build her for Elemental Mastery: 4pc Viridescent Venerer is her best set, with 4pc Desert Pavilion as an alternative. ATK%/Anemo/CRIT or a full EM focus both work depending on whether you want her personal damage or pure support. Weapons favor Lost Prayer, Kagura's Verity and The Widsith, with Hakushin Ring and Mappa Mare as free picks.\n\nHer best teams are Swirl DPS, Aggravate and Quicken comps where the EM buff directly raises reaction damage, and she pairs well with Nahida. Where she struggles: her on-field drifting state can be awkward to control, her personal damage is modest, and she has no shielding or healing. She is a thematically unique EM-buffing Anemo."
  }
};
